import type { Metadata } from 'next';
import './globals.css';
// import { gothicNeo } from './util/font';

import { ReactNode } from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	modal,
}: {
	children: ReactNode;
	modal: ReactNode;
}) {
	return (
		<html>
			<body>
				{children}
				{modal}
				<div id='portal-root' />
			</body>
		</html>
	);
}
