import type { Metadata } from 'next';
import './globals.css';
import { gothicNeo } from './util/font';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ko'>
			<body className={gothicNeo.className}>{children}</body>
		</html>
	);
}
